# Generated by Django 4.1.1 on 2022-09-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dinosaur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reino', models.CharField(max_length=255)),
                ('filo', models.CharField(max_length=255)),
                ('clado', models.CharField(max_length=255)),
                ('familia', models.CharField(max_length=255)),
                ('subFamilia', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=255)),
            ],
        ),
    ]
