# Generated by Django 4.1.1 on 2022-09-17 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCategoria', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dinosaur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('reino', models.CharField(max_length=255)),
                ('filo', models.CharField(max_length=255)),
                ('clado', models.CharField(max_length=255)),
                ('familia', models.CharField(max_length=255)),
                ('subFamilia', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dinopedia.category')),
            ],
            options={
                'db_table': 'dinosaur',
                'managed': True,
            },
        ),
    ]
