# Generated by Django 4.1.1 on 2022-10-05 19:27

import dinopedia.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('dinopedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinosaur',
            name='image',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=dinopedia.models.upload_to, variations={}),
        ),
    ]
