# Generated by Django 4.1.1 on 2022-10-25 17:20

import dinopedia.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dinosaur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', stdimage.models.StdImageField(force_min_size=False, upload_to=dinopedia.models.upload_to, variations={})),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('feeding_habit', models.CharField(max_length=255)),
                ('height', models.CharField(max_length=255)),
                ('length', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('short_description', models.TextField(max_length=510)),
                ('description', models.TextField(max_length=1024)),
            ],
            options={
                'db_table': 'dinosaur',
                'managed': True,
            },
        ),
    ]
