# Generated by Django 3.2.14 on 2022-10-25 13:17

import dinopedia.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCategoria', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dinosaur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', stdimage.models.StdImageField(force_min_size=False, upload_to=dinopedia.models.upload_to, variations={})),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('feeding_habit', models.CharField(max_length=255)),
                ('height', models.CharField(max_length=255)),
                ('length', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='dinopedia.category')),
            ],
            options={
                'db_table': 'dinosaur',
                'managed': True,
            },
        ),
    ]
